# Generated by Django 2.2.5 on 2019-11-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_type', models.CharField(db_index=True, max_length=10)),
                ('create_time', models.IntegerField(default=0)),
            ],
        ),
    ]
